"use client";

import {
  BadgeDollarSign,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  CheckCheck,
  ClipboardCheck,
  ClipboardList,
  CloudSun,
  Compass,
  Contact,
  FileChartColumn,
  FileClock,
  FileText,
  Globe2,
  GraduationCap,
  HandCoins,
  History,
  Home,
  Inbox,
  Landmark,
  Leaf,
  ListChecks,
  LockKeyhole,
  Map,
  Megaphone,
  Package,
  PackageCheck,
  PanelTop,
  ReceiptText,
  Scale,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sprout,
  Target,
  Telescope,
  ThermometerSun,
  TrendingUp,
  UserRound,
  UsersRound,
  Warehouse,
  Wheat,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "🏠": Home,
  "➕": ClipboardCheck,
  "🖊": CheckCheck,
  "📜": History,
  "📈": TrendingUp,
  "💡": ChartNoAxesCombined,
  "🌅": PanelTop,
  "🏆": BarChart3,
  "🌿": Leaf,
  "📊": BarChart3,
  "🎯": Target,
  "📖": BookOpen,
  "🔭": Telescope,
  "🌴": Sprout,
  "🌱": Sprout,
  "🗺️": Map,
  "📚": GraduationCap,
  "🐛": ShieldCheck,
  "🗓️": CalendarDays,
  "📱": Smartphone,
  "🧾": ReceiptText,
  "📦": Package,
  "🔢": ListChecks,
  "📥": PackageCheck,
  "🏷️": ShoppingCart,
  "💸": Banknote,
  "📋": FileText,
  "🔒": LockKeyhole,
  "🌾": Wheat,
  "🔏": FileClock,
  "📑": FileChartColumn,
  "🧮": Scale,
  "📒": Landmark,
  "💰": HandCoins,
  "👥": UsersRound,
  "💵": BadgeDollarSign,
  "🧷": ClipboardList,
  "📣": Megaphone,
  "🧭": Compass,
  "📨": Inbox,
  "🌤️": CloudSun,
  "🌡️": ThermometerSun,
  "⚙️": Settings,
  "👤": UserRound,
  "🌐": Globe2,
  "📬": Inbox,
  "💼": BriefcaseBusiness,
  "🤝": Contact,
  search: Search,
  inventory: Warehouse,
  organization: Building2,
  default: Boxes,
};

export function NavIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = ICONS[name] ?? ICONS.default;
  return <Icon size={size} strokeWidth={2} aria-hidden="true" focusable="false" />;
}
