"use client";

// Client-boundary re-export of @amrebeid/ui. The library's components rely on
// React context (createContext), which React Server Components do not provide,
// so the library must only ever be imported across a "use client" boundary.
// App code imports UI components from here, never from "@amrebeid/ui" directly
// in a Server Component.
export {
  ThemeProvider,
  AppShell,
  Breadcrumbs,
  Button,
  IconButton,
  Field,
  FormRow,
  Input,
  Textarea,
  Select,
  KpiCard,
  Stat,
  StatusPill,
  Tag,
  Alert,
  Card,
  Progress,
  VerdictBanner,
  Tabs,
  tabId,
  tabPanelId,
  DataTable,
  DescriptionList,
  Timeline,
  FileTimeline,
  ApprovalChain,
  LoopStepper,
  PalmGrid,
  EmptyState,
  Drawer,
  ConfirmDialog,
  ToastProvider,
  useToast,
  Modal,
  SearchInput,
  Skeleton,
  type NavItemData,
  type DataTableColumn,
  type SelectOption,
  type TimelineEvent,
  type ApprovalStep,
  type LoopStep,
  type PalmLine,
  type PalmStatus,
  type ConfirmDialogProps,
  type ConfirmTone,
  type ToastApi,
  type ToastOptions,
} from "@amrebeid/ui";
